package model;
// Generated 27/07/2015 21:42:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private int idgrupo;
     private String nome;
     private Set usuarios = new HashSet(0);

    public Grupo() {
    }

	
    public Grupo(String nome) {
        this.nome = nome;
    }
    public Grupo(String nome, Set usuarios) {
       this.nome = nome;
       this.usuarios = usuarios;
    }
   
    public int getIdgrupo() {
        return this.idgrupo;
    }
    
    public void setIdgrupo(int idgrupo) {
        this.idgrupo = idgrupo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


