package model;
// Generated 04/12/2014 12:06:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import model.util.IBaseEntity;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements IBaseEntity, java.io.Serializable {


     private int idgrupo;
     private String nome;
     private Set usuarios = new HashSet(0);
     private static final long serialVersionUID = 1L; 

    /**
     * Model Grupo
     */
    public Grupo() {
    }

    /**
     *
     * @param idgrupo
     * @param nome
     */
    public Grupo(int idgrupo, String nome) {
        this.idgrupo = idgrupo;
        this.nome = nome;
    }

    /**
     *
     * @param idgrupo
     * @param nome
     * @param usuarios
     */
    public Grupo(int idgrupo, String nome, Set usuarios) {
       this.idgrupo = idgrupo;
       this.nome = nome;
       this.usuarios = usuarios;
    }
   
    /**
     *
     * @return
     */
    public int getIdgrupo() {
        return this.idgrupo;
    }
    
    /**
     *
     * @param idgrupo
     */
    public void setIdgrupo(int idgrupo) {
        this.idgrupo = idgrupo;
    }

    /**
     *
     * @return
     */
    public String getNome() {
        return this.nome;
    }
    
    /**
     *
     * @param nome
     */
    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     *
     * @return
     */
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    /**
     *
     * @param usuarios
     */
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

    /**
     *
     * @return
     */
    @Override
    public Long getId() {
        return new Long(idgrupo);
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 17 * hash + this.idgrupo;
        hash = 17 * hash + Objects.hashCode(this.nome);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Grupo other = (Grupo) obj;
        if (this.idgrupo != other.idgrupo) {
            return false;
        }
        if (!Objects.equals(this.nome, other.nome)) {
            return false;
        }
        return true;
    }
 






}


