package model;
// Generated 27/07/2015 21:42:21 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private Grupo grupo;
     private String login;
     private byte[] senha;
     private String situacao;
     private String trocasenha;

    public Usuario() {
    }

	
    public Usuario(String login, byte[] senha, String situacao, String trocasenha) {
        this.login = login;
        this.senha = senha;
        this.situacao = situacao;
        this.trocasenha = trocasenha;
    }
    public Usuario(Grupo grupo, String login, byte[] senha, String situacao, String trocasenha) {
       this.grupo = grupo;
       this.login = login;
       this.senha = senha;
       this.situacao = situacao;
       this.trocasenha = trocasenha;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public byte[] getSenha() {
        return this.senha;
    }
    
    public void setSenha(byte[] senha) {
        this.senha = senha;
    }
    public String getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }
    public String getTrocasenha() {
        return this.trocasenha;
    }
    
    public void setTrocasenha(String trocasenha) {
        this.trocasenha = trocasenha;
    }




}


